import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import Header from '../components/Header'
import MedCard from '../components/MedCard'
import PlacesCard from '../components/PlacesCard'

export default function Home({data,data2}) {
  
  return (
    <div className="">
      <Head>
        <title>Appvisor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon (1).ico" />
      </Head>

      
        {/* Header Start*/}
        <Header/>
        {/* Header End */}

        {/* Banner Start */}
        <Banner/>
        {/* Banner End */}
      <main className="text-gray-500 max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6 ">
          <h2 className="text-4xl">Explore Places</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3">
            {/* Pull data from server */}
            {data?.map(place=>{
              return (
                <PlacesCard key={place.img} image={place.img} distance={place.distance} location={place.location}/>
              )
            })}
          </div>
        </section>
        <section className="pt-6">
          <h2 className="text-4xl">Travel Anywhere</h2>
          <div className="flex p-3 overflow-auto space-x-3 py-3 scrollbar-hide w-full">
            {
              data2?.map(data=>{
                return (
                  <MedCard key={data.img} image={data.img} title={data.title}/>
                )
              })
            }
          </div>
        </section>
        <section className="p-3 mt-20 mb-20 relative h-[300px] space-y-3">
            <Image src="https://links.papareact.com/4cj" layout="fill" objectFit="cover" className="rounded-xl"/>
          <div className="relative top-10 space-y-3">
            <h1 className="text-3xl text-gray-800 font-bold">The Greatest Outdoors</h1>
            <p className="text-sm text-gray-500">Wishlist curated by Appvisor</p>
            <button className="bg-purple-800 text-white rounded-2xl p-3">Get inspired</button>
          </div>
        </section>
      </main>
      <Footer />
      
    </div>
  )
}

export async function getStaticProps(){
  const data = await fetch(`https://links.papareact.com/pyp`).then(res=>{
    return res.json()
  })

  const data2 = await fetch(`https://links.papareact.com/zp1`).then(res=>{
    return res.json()
  })

  return {
    props: {
      data,
      data2
    }
  }
}
